### ISSUE TITLE
Create English translation for the instructions

### ISSUE THREAD

**Issue by laymonage** [laymonage/django-template-heroku#2]
I think this template can be useful for people outside of Fasilkom UI, so let's translate the instructions to English!

Ideally, I think it should be named `README.en.md`. Feel free to submit a PR for that, and I'll be glad to review it 😄 

**Please note that I only accept a PR for this issue if you speak Indonesian**.

Also note that I'm some kind of a perfectionist so be prepared for multiple revisions 😆

**Comment by ankurjain00** [comment]
Hi @laymonage I would like to contribute please assign the issue to me

**Comment by laymonage** [comment]
Hi @ankurjain00, unfortunately I cannot assign it to you unless you speak Indonesian.

**Comment by khadijahrizqy** [comment]
Hi @laymonage i would like to contribute! Can you assign it to me?

**Comment by laymonage** [comment]
Done, @khadijahrizqy!

**Comment by laymonage** [comment]
Hi @khadijahrizqy, it seems that someone else has already attempted to translate the instructions (see #3). Since you [haven't forked the repository](https://github.com/laymonage/django-template-heroku/network/members), I guess it's better if I reassign it so that there's no duplicated work. Sorry!

**Comment by raihan71** [comment]
hi, @laymonage can you assign it to me? I already made PR, terima kasih.

**Comment by laymonage** [comment]
Closed in #3.
